apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dash-apps
  namespace: monitoring
data:
  apps-overview.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  { "color": "green", "value": null }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
          "id": 1,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "pluginVersion": "11.0.0",
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(up)",
              "refId": "A"
            }
          ],
          "title": "Targets UP",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  { "color": "green", "value": null }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
          "id": 2,
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "pluginVersion": "11.0.0",
          "targets": [
            {
              "editorMode": "code",
              "expr": "count(kube_pod_info)",
              "refId": "A"
            }
          ],
          "title": "Pods no cluster",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "cores"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
          "id": 4,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\",image!=\"\"}[5m]))",
              "refId": "A"
            }
          ],
          "title": "CPU total",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "bytes"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
          "id": 5,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(container_memory_working_set_bytes{container!=\"\",image!=\"\"})",
              "refId": "A"
            }
          ],
          "title": "Memória total",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "Bps"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
          "id": 6,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
              "refId": "A"
            }
          ],
          "title": "RX total",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "Bps"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
          "id": 7,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
              "refId": "A"
            }
          ],
          "title": "TX total",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "max": 1,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  { "color": "red", "value": 0 },
                  { "color": "green", "value": 1 }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
          "id": 3,
          "options": {
            "displayMode": "lcd",
            "minVizHeight": 10,
            "minVizWidth": 0,
            "namePlacement": "left",
            "orientation": "horizontal",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "showUnfilled": true,
            "sizing": "auto",
            "valueMode": "color"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "max by (pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\"})",
              "legendFormat": "{{pod}}",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Pods status (1 = Running / 0 = Fora)",
          "type": "bargauge"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "cores"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
          "id": 8,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}[5m]))",
              "refId": "A"
            }
          ],
          "title": "CPU do pod selecionado",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "bytes"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
          "id": 9,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"})",
              "refId": "A"
            }
          ],
          "title": "Memória do pod selecionado",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "Bps"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
          "id": 10,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
              "refId": "A"
            }
          ],
          "title": "RX do pod selecionado",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "Bps"
            },
            "overrides": []
          },
          "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
          "id": 11,
          "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": ["lastNotNull"],
              "fields": "",
              "values": false
            },
            "textMode": "auto"
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))",
              "refId": "A"
            }
          ],
          "title": "TX do pod selecionado",
          "type": "stat"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "cores"
            },
            "overrides": []
          },
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
          "id": 12,
          "options": {
            "legend": {
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single"
            }
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"}[5m]))",
              "legendFormat": "{{pod}}",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "CPU ao longo do tempo",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "Prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "unit": "bytes"
            },
            "overrides": []
          },
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
          "id": 13,
          "options": {
            "legend": {
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single"
            }
          },
          "targets": [
            {
              "editorMode": "code",
              "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", image!=\"\"})",
              "legendFormat": "{{pod}}",
              "range": true,
              "refId": "A"
            }
          ],
          "title": "Memória ao longo do tempo",
          "type": "timeseries"
        }
      ],
      "schemaVersion": 39,
      "tags": [
        "apps",
        "prometheus",
        "kubernetes"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": true,
              "text": ".*",
              "value": ".*"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "Prometheus"
            },
            "definition": "label_values(kube_pod_info, namespace)",
            "hide": 0,
            "includeAll": true,
            "label": "Namespace",
            "multi": false,
            "name": "namespace",
            "options": [],
            "query": {
              "qryType": 1,
              "query": "label_values(kube_pod_info, namespace)",
              "refId": "Prometheus-namespace"
            },
            "refresh": 1,
            "regex": "",
            "sort": 1,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": ".*",
              "value": ".*"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "Prometheus"
            },
            "definition": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)",
            "hide": 0,
            "includeAll": true,
            "label": "Pod",
            "multi": true,
            "name": "pod",
            "options": [],
            "query": {
              "qryType": 1,
              "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)",
              "refId": "Prometheus-pod"
            },
            "refresh": 1,
            "regex": "",
            "sort": 1,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-30m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Apps Overview",
      "version": 3
    }