nameOverride: go-server-time-api

replicaCount: 1

image:
  repository: ghcr.io/analiviameister/go-server-time-api
  tag: "222a7d1"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  host: go-server-time-api.127.0.0.1.nip.io
  path: /

env:
  - name: PORT
    value: "8080"
  - name: REDIS_ADDR
    value: "redis-master.infra.svc.cluster.local:6379"
  - name: REDIS_PASSWORD
    value: ""

resources: {}