nameOverride: python-text-display-api

replicaCount: 1

image:
  repository: ghcr.io/analiviameister/python-text-display-api
  tag: "678bcf3"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  host: python-text-display-api.127.0.0.1.nip.io
  path: /

env:
  - name: PORT
    value: "8080"
  - name: REDIS_HOST
    value: "redis-master.infra.svc.cluster.local"
  - name: REDIS_PASSWORD
    value: ""

resources: {}