apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/analiviameister/cq-infra-gitops.git
    targetRevision: HEAD
    path: observability/grafana/configmaps
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true